---
forum:
    url: "https://community.example.com/"
    name: "My Minecraft Forum"
    apikey: "SECRETPASSWORD"
socketio:
    address: "https://live.example.com/"
    transports:
    - polling
    - websocket
    namespace: "plugins.MinecraftIntegration"
messages:
    nodebb:
        socketio:
            address:
                get:
                    - "The websocket domain is set to %live%"
                set:
                    - "Set the websocket domain to %live%"
            transports:
                get:
                    - "Websocket transports are %transports%"
                add:
                    - "Added websocket transport %transport%"
                remove:
                    - "Removed websocket transport %transport%"
            namespace:
                get:
                    - "Websocket namespace is %transports%"
                set:
                    - "Removed websocket transport %transport%"
        help:
            - "&f[&6NodeBB Integration&f]"
            - "&4=&c=&6=&e=&a=&3=&b=&9=&1=&d=&5=&4=&c=&6=&e=&a=&2=&3=&b="
            - "&fCommands:"
            - "&e/nodebb reload &r- Reloads config and reconnects to the forum."
            - "&e/nodebb key [key] &r- Get or set the forum API key."
            - "&e/nodebb name [name] &r- Get or set the forum name."
            - "&e/nodebb url [url] &r- Get or set the forum url."
            - "&e/nodebb debug &r- Displays information useful for fixing errors."
    register:
        Alert:
            - "Registering your player on %forumname% (%forumurl%&r)"
        Disconnected:
            - "Sorry! The server isn't currently connected to the forum."
        AssertParameters:
            - "Copy your player key from"
            - "%forumurl%minecraft/register&r"
            - "then use the command /register [key]"
        RegSuccess:
            - "Success! Registered your player on %forumname%"
        CreatedNewAccount:
            - "Success! Created a new account on %forumname%"
        FailKey:
            - "Invalid Key"
        FailDB:
            - "Error on forum. Please inform an administrator."
        BadRes:
            - "Internal error. Please inform an administrator."
        FailData:
            - "Data error. Please inform an administrator."
        ParsingError:
            - "Parsing error. Please inform an administrator."
version: "0.8.0-alpha.11"